apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: eee
spec:
  serviceName: eee
  replicas: 2
  template:
    metadata:
      labels:
        app: eee
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: eee
        image: killonexx/hanshow:esl-2.2.2-v1
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 37021
          name: tcp
        - containerPort: 37022
          name: sslk
        - containerPort: 8800
          name: g1-udp
        - containerPort: 5649
          name: g1-tcp
        - containerPort: 21
          name: g1-ftp
        resources:
          limits:
          #  cpu: "500m"
            memory: 2Gi
          requests:
          # cpu: "500m"
           memory: 2Gi
        env:
          - name: SW_URL
            value: "tomcat-0.tomcat:8080"
          - name: APG1
            value: "false"
        volumeMounts:
        - name: data
          mountPath: /esl_data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: data
      resources:
        requests:
          storage: 2Gi
