apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: nginx
data:
  stream.conf: |
    server {
       listen      37021;
       proxy_pass  esl-0.esl.default.svc.cluster.local:37021;
    }