apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: ssl
  - port: 8080
    targetPort: 8080
    name: shop-web
  - port: 3306
    targetPort: 3306
    name: mysql
  - port: 9000
    targetPort: 9000
    name: esl-http-1
  - port: 37021
    targetPort: 37021
    name: esl-tcp-1
  - port: 9001
    targetPort: 9001
    name: esl-http-2
  - port: 37022
    targetPort: 37022
    name: esl-tcp-2
  selector:
    app: nginx